# Generated by Django 3.2.5 on 2021-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naengpa', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
