# Generated by Django 3.2.5 on 2021-07-27 06:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naengpa', '0007_alter_recipe_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=''),
        ),
    ]
