# Generated by Django 3.2.5 on 2021-07-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naengpa', '0008_auto_20210727_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
