# Generated by Django 3.2.5 on 2021-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naengpa', '0012_alter_recipe_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
