# Generated by Django 3.2.5 on 2021-08-07 07:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('naengpa', '0016_auto_20210806_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to=''),
        ),
    ]
